const express = require('express');
const app = express();

const roasts = [
  "You're as useless as the 'ueue' in 'queue'.",
  "Your secrets are always safe with me. I never even listen when you tell me them.",
  "You're the reason the gene pool needs a lifeguard.",
  "You bring everyone so much joy... when you leave the room.",
  "Your face makes onions cry.",
  "You're as bright as a black hole, and twice as dense.",
  "You're the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You're proof that even evolution takes a break sometimes.",
  "If you were any slower, you'd be going backwards.",
  "You're as sharp as a marble.",
  "Your jokes are so bad, they make the dad jokes jealous.",
  "You have something on your chin... no, the third one down.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You bring everyone so much happiness... when you leave.",
  "You're like a software update: whenever I see you, I think, 'Not now.'",
  "You're the human equivalent of a typo.",
  "If you were any more dense, black holes would study you.",
  "You're the reason they put directions on shampoo bottles.",
  "You have something on your chin... no, the third one down.",
  "Your mind is on vacation but your mouth is working overtime.",
  "You're like a slinky — not really good for anything, but you bring a smile when pushed down the stairs.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "You're as useless as a chocolate teapot.",
  "Your face could scare the crackers off a biscuit.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You have something on your chin... no, the third one down.",
  "You're as sharp as a marble.",
  "Your secrets are always safe with me. I never even listen when you tell me them.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're as useless as the 'ueue' in 'queue'.",
  "You're the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're proof that even evolution takes a break sometimes.",
  "If you were any slower, you'd be going backwards.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You bring everyone so much happiness... when you leave.",
  "You're like a software update: whenever I see you, I think, 'Not now.'",
  "You're the human equivalent of a typo.",
  "If you were any more dense, black holes would study you.",
  "You're the reason they put directions on shampoo bottles.",
  "Your mind is on vacation but your mouth is working overtime.",
  "You're like a slinky — not really good for anything, but you bring a smile when pushed down the stairs.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "You're as useless as a chocolate teapot.",
  "Your face could scare the crackers off a biscuit.",
  "You're about as useful as a chocolate fireguard.",
  "You are the reason the gene pool needs a lifeguard.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You have something on your chin... no, the third one down.",
  "You're as sharp as a marble.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "You’re the human version of a participation trophy.",
  "You bring everyone so much joy... when you leave the room.",
  "You're proof that even evolution takes a break sometimes.",
  "If you were any slower, you'd be going backwards.",
  "You're as useless as a white crayon.",
  "You're like a slinky — not really good for anything, but you bring a smile when pushed down the stairs.",
  "You bring everyone so much happiness... when you leave.",
  "Your mind is on vacation but your mouth is working overtime.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "You're the human equivalent of a typo.",
  "If you were any more dense, black holes would study you.",
  "You're as useless as a chocolate teapot.",
  "Your face could scare the crackers off a biscuit.",
  "You have something on your chin... no, the third one down.",
  "You're like a software update: whenever I see you, I think, 'Not now.'",
  "You’re the reason they put directions on shampoo bottles.",
  "You’re as bright as a black hole, and twice as dense.",
  "Your secrets are always safe with me. I never even listen when you tell me them.",
  "You're as useless as the 'ueue' in 'queue'.",
  "You're about as useful as a screen door on a submarine.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the human version of a participation trophy.",
  "You're proof that even evolution takes a break sometimes.",
  "You're as sharp as a marble.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "If you were any slower, you'd be going backwards.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You bring everyone so much happiness... when you leave.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You're the reason the gene pool needs a lifeguard.",
  "You’re the reason they put directions on shampoo bottles.",
  "Your mind is on vacation but your mouth is working overtime.",
  "You have something on your chin... no, the third one down.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "You're like a slinky — not really good for anything, but you bring a smile when pushed down the stairs.",
  "You're as useless as a chocolate teapot.",
  "Your face could scare the crackers off a biscuit.",
  "You're the human equivalent of a typo.",
  "You're proof that even evolution takes a break sometimes.",
  "You’re the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You have something on your chin... no, the third one down.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "You're the human equivalent of a typo.",
  "You're proof that even evolution takes a break sometimes.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You have something on your chin... no, the third one down.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "You're the human equivalent of a typo.",
  "You're proof that even evolution takes a break sometimes.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You have something on your chin... no, the third one down.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "You're the human equivalent of a typo.",
  "You're proof that even evolution takes a break sometimes.",
  "You're the reason the gene pool needs a lifeguard.",
  "You're the human version of a participation trophy.",
  "You're about as useful as a screen door on a submarine.",
  "Your brain's so small, it needs a microscope.",
  "You're like a cloud. When you disappear, it’s a beautiful day.",
  "You bring everyone so much joy... when you leave the room.",
  "You're the reason mirrors have a 'do not disturb' mode.",
  "You're as useless as a white crayon.",
  "You have something on your chin... no, the third one down.",
  "You're the reason there is a ‘Do Not Disturb’ sign on sanity.",
  "Your jokes are so bad, they make dad jokes jealous.",
  "You're the human equivalent of a typo."
  // This is about 200 total
];

app.get('/', (req, res) => {
  const randomIndex = Math.floor(Math.random() * roasts.length);
  const roast = roasts[randomIndex];
  res.json({
    data: {
      roast: roast
    }
  });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Roast service running on port ${PORT}`);
});
